<a href="https://colab.research.google.com/github/hassaan871/DeepLearning-for-CV-with-python-and-TensorFlow/blob/main/TensorFlow_Tensors_Neuralearn_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Learning TensorFlow**
-Tensors are multidimensional arrays

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [5]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [6]:
tensor_three_d = tf.constant([
    [[1,2,3],[4,5,6]],
    [[4,5,6],[3,2,1]],
    [[9,0,1],[7,4,3]],
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [3 2 1]]

 [[9 0 1]
  [7 4 3]]], shape=(3, 2, 3), dtype=int32)


In [7]:
print(tensor_zero_d.shape)
print(tensor_one_d.shape)
print(tensor_two_d.shape)
print(tensor_three_d.shape)

()
(3,)
(3,)
(3, 3)
(3, 2, 3)


In [8]:
print(tensor_zero_d.ndim)
print(tensor_one_d.ndim)
print(tensor_two_d.ndim)
print(tensor_three_d.ndim)

0
1
2
3


In [13]:
tensor_four_d = tf.constant([

    [ [[1,2,3],[4,5,6]],
    [[4,5,6],[3,2,1]],
    [[9,0,1],[7,4,3]],],

    [ [[1,2,3],[4,5,6]],
    [[4,5,6],[3,2,1]],
    [[9,0,1],[7,4,3]],],

    [ [[1,2,3],[4,5,6]],
    [[4,5,6],[3,2,1]],
    [[9,0,1],[7,4,3]],]

],dtype=tf.float32)

print(tensor_four_d)
print(tensor_four_d.shape)
print(tensor_four_d.ndim)

tf.Tensor(
[[[[1. 2. 3.]
   [4. 5. 6.]]

  [[4. 5. 6.]
   [3. 2. 1.]]

  [[9. 0. 1.]
   [7. 4. 3.]]]


 [[[1. 2. 3.]
   [4. 5. 6.]]

  [[4. 5. 6.]
   [3. 2. 1.]]

  [[9. 0. 1.]
   [7. 4. 3.]]]


 [[[1. 2. 3.]
   [4. 5. 6.]]

  [[4. 5. 6.]
   [3. 2. 1.]]

  [[9. 0. 1.]
   [7. 4. 3.]]]], shape=(3, 3, 2, 3), dtype=float32)
(3, 3, 2, 3)
4


In [15]:
tensor_one_d = tf.constant([0.0,2,3-4],dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
boolean_casted_tensor_one_d = tf.cast(casted_tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)
print(boolean_casted_tensor_one_d)

tf.Tensor([ 0.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor([ 0  2 -1], shape=(3,), dtype=int16)
tf.Tensor([False  True  True], shape=(3,), dtype=bool)


In [17]:
tensor_bool = tf.constant([True, True, False, True],dtype=tf.bool)
print(tensor_bool)

tf.Tensor([ True  True False  True], shape=(4,), dtype=bool)


In [21]:
tensor_string = tf.constant(["Hello World", "hi"])
print(tensor_string)
print(tensor_string.shape)
print(tensor_string.ndim)

tf.Tensor([b'Hello World' b'hi'], shape=(2,), dtype=string)
(2,)
1
